Add unit test for components, login and registration page
nitishsharmaquo/social-directory pull request #6
Opened 2020-08-24 09:04 UTC by nitishsharmaquo

Unit Tests added for components and pages

2020-08-26 06:10 UTC, kimmi-kumari commented on .gitignore
> +__snapshots__
This should not be in .gitignore

2020-08-26 06:14 UTC, kimmi-kumari requested changes
There is one small comment. Rest all is good.

2020-08-26 06:20 UTC, nitishsharmaquo commented on .gitignore
> +__snapshots__
Updated

2020-08-27 05:05 UTC, kimmi-kumari approved these changes

2020-08-27 05:07 UTC, merged